config/routes.rb
Ipt::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :news

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/news.rb
class News < ActiveRecord::Base
	validates :title, :length => { :maximum => 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/home/index.html.erb
<h1>Добро пожаловать</h1>

Государственное образовательное учреждение среднего профессионального образования Свердловской области «Ирбитский политехникум» одно из старейших профессиональных образованных учреждений города Ирбита.

Кого и чему здесь учат? Мы уверены, что учим людей способных, знающих и умеющих трудится. Мы учим мыслить, думать, ставить вопросы, уметь решать поставленные задачи. Дух и стиль нашего образовательного учреждения – чувствовать себя нужным и успешным.

Более 700 человек осваивает 33 профессий и специальностей начального и среднего профессионального образования. Юноши и девушки обучаются слесарному, строительному, токарному, поварскому, швейному, транспортному делу и работе на компьютерной технике.

Жизнь становится ещё интереснее, когда после уроков можно заниматься в кружках, секциях, объединениях по интересам. Здесь находят друзей, обретают социальную зрелость и смысл своей профессии.

79 педагогических работников нашего политехникума владеют разнообразными тактиками педагогической поддержки, обеспечивающей развитие личности обучающегося. Стратегическая задача педагогов не проверить знания, а увлечь, привить интерес, научить способам действия, решать проблемы.

Приходите к нам учиться, и Вы в этом убедитесь. Мы ждем Вас!

app/views/home/index.html.haml
%h1 Добро пожаловать

%p Государственное образовательное учреждение среднего профессионального образования Свердловской области «Ирбитский политехникум» одно из старейших профессиональных образованных учреждений города Ирбита.

%p Кого и чему здесь учат? Мы уверены, что учим людей способных, знающих и умеющих трудится. Мы учим мыслить, думать, ставить вопросы, уметь решать поставленные задачи. Дух и стиль нашего образовательного учреждения – чувствовать себя нужным и успешным.

%p Более 700 человек осваивает 33 профессий и специальностей начального и среднего профессионального образования. Юноши и девушки обучаются слесарному, строительному, токарному, поварскому, швейному, транспортному делу и работе на компьютерной технике.

%p Жизнь становится ещё интереснее, когда после уроков можно заниматься в кружках, секциях, объединениях по интересам. Здесь находят друзей, обретают социальную зрелость и смысл своей профессии.

%p 79 педагогических работников нашего политехникума владеют разнообразными тактиками педагогической поддержки, обеспечивающей развитие личности обучающегося. Стратегическая задача педагогов не проверить знания, а увлечь, привить интерес, научить способам действия, решать проблемы.

%p Приходите к нам учиться, и Вы в этом убедитесь. Мы ждем Вас!

app/views/home/index.html.slim
h1 Добро пожаловать

p Государственное образовательное учреждение среднего профессионального образования Свердловской области «Ирбитский политехникум» одно из старейших профессиональных образованных учреждений города Ирбита.

p Кого и чему здесь учат? Мы уверены, что учим людей способных, знающих и умеющих трудится. Мы учим мыслить, думать, ставить вопросы, уметь решать поставленные задачи. Дух и стиль нашего образовательного учреждения – чувствовать себя нужным и успешным.

p Более 700 человек осваивает 33 профессий и специальностей начального и среднего профессионального образования. Юноши и девушки обучаются слесарному, строительному, токарному, поварскому, швейному, транспортному делу и работе на компьютерной технике.

p Жизнь становится ещё интереснее, когда после уроков можно заниматься в кружках, секциях, объединениях по интересам. Здесь находят друзей, обретают социальную зрелость и смысл своей профессии.

p 79 педагогических работников нашего политехникума владеют разнообразными тактиками педагогической поддержки, обеспечивающей развитие личности обучающегося. Стратегическая задача педагогов не проверить знания, а увлечь, привить интерес, научить способам действия, решать проблемы.

p Приходите к нам учиться, и Вы в этом убедитесь. Мы ждем Вас!

app/views/layouts/application.html.slim
doctype html
html
  head
    title ГБОУ СПО СО "Ирбитский политехникум"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    #page
      #header
        / = image_tag("top.jpg", :alt => "Top", :class => "round")
      #content
        #left_content
          
        #center_content
          = yield
      #footer

app/views/news/_form.html.slim
= form_for @news do |f|
  -if @news.errors.any?
    #error_explanation
      h2 = "#{pluralize(@news.errors.count, "error")} prohibited this news from being saved:"
      ul
        - @news.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :extract
    = f.text_field :extract
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/news/edit.html.slim
h1 Editing news

== render 'form'

= link_to 'Show', @news
'|
= link_to 'Back', news_index_path

app/views/news/index.html.slim
h1 Listing news

table
  tr
    th Title
    th Extract
    th Content
    th
    th
    th

  - @news.each do |news|
    tr
      td= news.title
      td= news.extract
      td= news.content
      td= link_to 'Show', news
      td= link_to 'Edit', edit_news_path(news)
      td= link_to 'Destroy', news, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New News', new_news_path

app/views/news/new.html.slim
h1 New news

== render 'form'

= link_to 'Back', news_index_path

app/views/news/show.html.slim
p#notice = notice

p
  b Title:
  = @news.title
p
  b Extract:
  = @news.extract
p
  b Content:
  = @news.content

= link_to 'Edit', edit_news_path(@news)
'|
= link_to 'Back', news_index_path